language: rust

cache: cargo

os:
- linux
- osx

before_script:
  - rustup component add rustfmt

rust:
  - stable
  - nightly

script:
  - cargo fmt --all -- --check
  - cargo test --no-default-features
  - cargo test --all-features
