language: rust

cache: cargo

dist: xenial

os:
  - linux
  - osx

addons:
  homebrew:
     packages:
         - sqlite3

env:
  - RUST_BACKTRACE=1 PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"

before_script:
  - rustup component add rustfmt

rust:
  - stable
  - nightly

script:
  - cargo fmt --all -- --check
  - cargo test --no-default-features
  - cargo test --all-features
