language: rust

cache: cargo

dist: xenial

os:
  - linux
  - osx

env:
  - RUST_BACKTRACE=1

before_script:
  - rustup component add rustfmt

rust:
  - stable
  - nightly

script:
  - cargo fmt --all -- --check
  - cargo test --no-default-features
  - cargo test --all-features
